#trigger:
#  - main

pool: slave


variables:
  COMPONENT: 'dispatch'

resources:
  repositories:
    - repository: templates
      type: github
      name: GurukaYadav/roboshop-azure-devops-templates
      endpoint: GurukaYadav

stages:
  - template: golang.yml@templates